sources:
  - name: silver
    tables:
      - name: orders
        meta:
          external_location: "../data/silver/orders.parquet"
      - name: delivery_timeline
        meta:
          external_location: "../data/silver/delivery_timeline.parquet"