version: 2

models:
  - name: 01_SLA_breach_analysis
    columns:
      - name: city
        tests: [not_null]

  - name: 04_riders_performance
    columns:
      - name: rider_id
        tests: [not_null]

  - name: 05_weekly_trends
    columns:
      - name: week
        tests: [not_null]